-- 回滚所有表（警告：会删除所有数据！）
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS import_rows CASCADE;
DROP TABLE IF EXISTS import_sheets CASCADE;
DROP TABLE IF EXISTS imports CASCADE;
DROP TABLE IF EXISTS traced_targets CASCADE;
DROP TABLE IF EXISTS device_tags CASCADE;
DROP TABLE IF EXISTS tag_batches CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS event_followups CASCADE;
DROP TABLE IF EXISTS mined_event_iocs CASCADE;
DROP TABLE IF EXISTS mined_event_devices CASCADE;
DROP TABLE IF EXISTS mined_events CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS config CASCADE;
